name: ultimatefix
description: Team Build Pro (Dart-only with SDK)
publish_to: 'none'
version: 1.0.52+82

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.20.2
  path: ^1.8.3
  firebase_auth_rest: ^2.1.1
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.4
  uuid: ^4.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  dropdown_search: ^6.0.2
  multi_select_flutter: ^4.1.3
  in_app_purchase: ^3.2.3
  cloud_functions: ^5.5.1
  firebase_messaging: ^15.2.6
  country_picker: ^2.0.20
  firebase_core: ^3.13.1
  crypto: ^3.0.6
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  firebase_remote_config: ^5.0.0
  rxdart: ^0.27.7
  app_links: ^6.4.0
  in_app_review: ^2.0.10
  flutter_launcher_icons: ^0.13.1
  app_badge_plus: ^1.1.4
  google_fonts: ^6.3.0
  flutter_branch_sdk: ^8.0.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.prod
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/team-build-pro.png"